### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/shellcheck-repl#1]
@xPMo, I'd like to add a FOSS license to this code base already now.  I don't mind which is one.  Do you have any preferences?

I see you've used [ISC](https://opensource.org/licenses/ISC) in the past (similar to [MIT](https://opensource.org/licenses/MIT)).  The [ShellCheck](https://github.com/koalaman/shellcheck) tool uses [GPL-3.0](https://opensource.org/licenses/GPL-3.0) - I'm happy to "inherit" that one too.

**Comment by xPMo** [comment]
I like ISC or MIT for shell things like this, it means people can look at the code and drop it right into a personal project (like trying to write their own bash widget) unrestricted. I don't think we need to force others to open source if they choose to copy (like GPL does). Agree?

EDIT: Bump this thread when you make it, I'll PR with a GPG-signed commit adding my name to the license.

**Comment by HenrikBengtsson** [comment]
Sounds all good to me. Let's go with ISC for the license.

**Comment by HenrikBengtsson** [comment]
I might have misunderstood your "Bump this thread when you make it, ..." comment.  I went ahead a added a LICENSE file (develop branch).  Please add your name as a Copyright holder - I guess that's what you meant.
